### ISSUE TITLE
Error while using the div scrapper

### ISSUE THREAD

**Issue by GSnchez** [eshinhw/quant-notebooks#1]
I got this error while using your dividend scrapper. Amazing content btw.

line 84, in <module>
    100 * (div_data[symbol][0][year] - div_data[symbol][0][year - 1]) /
KeyError: 2004

**Comment by eshinhw** [comment]
Hi, Thanks for checking out my codes.

There are several files which work with stock dividend, so may I ask which python file you got the error from? Is this one of the jupyter notebooks or actual py files?

I think the main reason for this kind of error is you have incorrectly selected minimum years, so the year in the calculation is not available. Please check min_year_variable in the code in the meantime.

**Comment by GSnchez** [comment]
Get Dividend Data from Stocks in S&P500.ipynb --> Is this file

min_div_pay_years = x, trying to change this variable but doesn't seems to work.

**Comment by eshinhw** [comment]
I see where the error is coming from. Before it saves the data as json in the end, it calculates 5 years average dividend growth and 15 years average dividend growth using annual dividend data we gathered. That means every symbol has at least more than 16 years of yearly dividend data to compute 15 years average. If min_div_pay_years <= 16 or this 15 years threshold, it will throw an error as there are not enough yearly data to compute 15 years average dividend growth.

I initially wrote this script to analyze the companies who have paid out dividends more than 50 years (setting min_div_pay_years = 50) so there was no problem calculating average growth for 15 years period.

If you just want to collect annual dividend data but not historical averages, you can comment out average dividend growth calculation part. If you still want to get historical average growth, you can set min_div_pay_years = 17 at minimum to give enough yearly data to compute 15 years average growth. Or you can adjust the period of historical average growth for your interest by changing 'prev_five_yrs' and 'prev_fifteen_yrs' variables below.

for symbol in div_data.keys():
    start_year = list(div_data[symbol][0].keys())[0]
    last_year = dt.datetime.today().year - 1
    prev_five_yrs = last_year - 6
    prev_fifteen_yrs = last_year - 16
    print(f"working on {symbol} | start year = {start_year}")

**Comment by GSnchez** [comment]
All clear, thank you so much for your time and explanation. Nice content.
